### PR TITLE
[WIP] gcc: xtensa.md: Add bswap[sd]i2

### PR DESCRIPTION
**Pull request by jjsuwa-sys3175**
/cc @jcmvbkbc

now `__builtin_bswap32/64()` are inlined and are 5 and 9 insns, respectively.

(note: 9 insns may be slightly big to be inlined...)

### CODE REVIEW

**Comment by jcmvbkbc** [comment]
Interesting. If you take a look at the xtensa ISA book chapter 8 there's a section "Instruction idioms" with the following code for bswap, which is even shorter:
```
ssai 8
srli ax, ay, 16
src ax, ax, ay
src ax, ax, ax
src ax, ay, ax
```
I turned it into
```
diff --git a/gcc/config/xtensa/xtensa.md b/gcc/config/xtensa/xtensa.md
index 462a7244a35d..a75de6551afc 100644
--- a/gcc/config/xtensa/xtensa.md
+++ b/gcc/config/xtensa/xtensa.md
@@ -469,6 +469,18 @@
 })
 
 ^L
+;; Byte swap
+
+(define_insn "bswapsi2"
+  [(set (match_operand:SI 0 "register_operand" "=&a")
+       (bswap:SI (match_operand:SI 1 "register_operand" "r")))]
+  ""
+  "ssai\t8;srli\t%0, %1, 16;src\t%0, %0, %1;src\t%0, %0, %0;src\t%0, %1, %0"
+  [(set_attr "type"    "arith")
+   (set_attr "mode"    "SI")
+   (set_attr "length"  "15")])
+
+^L
 ;; Negation and one's complement.
 
 (define_insn "negsi2"
```
and it gets used for both bswapsi2 and bswapdi2, the only thing that doesn't look right to me is that extra register moves that gcc does in the following examples:

```
unsigned long fm32(unsigned long *v)
{
        return __builtin_bswap32(*v);
}

unsigned long long fm64(unsigned long long *v)
{
        return __builtin_bswap64(*v);
}
```
```
        .file   "test.c"
        .text
        .align  4
        .global fm32
        .type   fm32, @function
fm32:   
        entry   sp, 32
        l32i.n  a2, a2, 0
        ssai    8;srli  a3, a2, 16;src  a3, a3, a2;src  a3, a3, a3;src  a3, a2, a3
        mov.n   a2, a3
        retw.n
        .size   fm32, .-fm32
        .align  4
        .global fm64
        .type   fm64, @function
fm64:   
        entry   sp, 32
        l32i.n  a3, a2, 0
        l32i.n  a2, a2, 4
        ssai    8;srli  a4, a3, 16;src  a4, a4, a3;src  a4, a4, a4;src  a4, a3, a4
        mov.n   a3, a4
        ssai    8;srli  a4, a2, 16;src  a4, a4, a2;src  a4, a4, a4;src  a4, a2, a4
        mov.n   a2, a4
        retw.n
        .size   fm64, .-fm64
        .ident  "GCC: (GNU) 11.0.0 20201217 (experimental)"
```

**Comment by jjsuwa-sys3175** [comment]
@jcmvbkbc
Great! worth incorporating as builtin.

```
(define_insn_and_split "bswapdi2"
  [(set (match_operand:DI 0 "register_operand" "=a")
	(bswap:DI (match_operand:DI 1 "register_operand" "r")))]
  ""
  "#"
  ""
  [(parallel [(set (subreg:SI (match_dup 0) 0) (bswap:SI (subreg:SI (match_dup 1) 4)))
	      (set (subreg:SI (match_dup 0) 4) (bswap:SI (subreg:SI (match_dup 1) 0)))])]
  ""
  [(set_attr "type"	"arith")
   (set_attr "mode"	"DI")])
```
(sorry, not tested yet)

**Comment by jcmvbkbc** [comment]
> (define_insn_and_split "bswapdi2"
Why is it needed? I see gcc using bswapsi2 pattern to implement bswapdi2 even without it.

**Comment by jcmvbkbc** [comment]
> +(define_insn "bswapdi2"

Oh, ok, I understand that (:
I also think it's worth limiting both these patterns to `!optimize_size` and providing libgcc alternatives. I'll submit that version.

**Comment by jcmvbkbc** [comment]
[Done](https://gcc.gnu.org/git/?p=gcc.git;a=commitdiff;h=18e86fae2a14f78e70aae06afce6bb9853068bb1).

**Comment by jjsuwa-sys3175** [comment]
@jcmvbkbc thx for merging to upstream.

This PR has been closed, because the upstream version should be preferred.

**Pull request closed without merging**
