### PR TITLE
Fix for __func__, etc. not emitted to PROGMEM

### PR DESCRIPTION
**Pull request by mikee47**
See https://github.com/earlephilhower/newlib-xtensa/issues/5.

(Raised issue in wrong repo - sorry!)

### CODE REVIEW

**Comment by earlephilhower** [comment]
There were other changes in the GCC PR that this doesn't back out.  I'm a little worried about something going weird because of it.

I'm doing a test build right now with a patch that is basically a patch -R of the PR in question (undoes cp-tree, decl, lambda, and pt). 

I've also transferred the issue to this repo, for sanity's sake...

**Comment by mikee47** [comment]
There's a few extra bits in that PR which should probably stay in as they relate to use within templated code. I spent a fair bit of time tracking down the 'minimal' patch for this, if you dig through the `cp_finish_decl()` call which was replaced it's in there.

If you want to test this patch I've uploaded a build to my repo here https://github.com/mikee47/esp-quick-toolchain/releases

**Comment by earlephilhower** [comment]
OK, fair enough.  I read thru the mailing list traffic on the patch and we'll give this minimal one a go.  Thanks!

**Comment by mikee47** [comment]
Cool :-) Thanks.

**Pull request merged**
